repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: no-commit-to-branch
        name: Branch protection
        args: [--branch, master, --branch, main]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: env PYTHONPATH="." python3 -m pylint feedback_summarization
        language: system
        always_run: true
        pass_filenames: false
